site_name: Nightscout
theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
    logo: NS-logo.png
    favicon: NS-logo-std.png
    palette:
      primary: black
    nav_style: primary
extra_css:
    - css/admonitions.css
markdown_extensions: 
    - admonition
    - toc:
        permalink: ⌁

nav:
- Introduction:
    - 'What is Nightscout?': 'index.md'
    - 'How do I upload my data?': 'uploader/uploaders.md'
- DIY Nightscout:
    - 'Classic DIY Installation': 'nightscout/new_user.md'
    - 'GitHub': 'nightscout/github.md'
    - 'MongoDB Atlas database': 'vendors/mongodb/atlas.md'
    - 'Heroku Hobby plan': 'vendors/heroku/new_user.md'
    - 'Railway (method 1)': 'vendors/railway/new_user.md'
    - 'Railway (method 2)': 'vendors/railway/new_user2.md'
    - 'Migration to Railway': 'vendors/railway/migration.md'
    - 'Fly.io': 'vendors/fly.io/new_user.md'
    - 'Migration to Fly.io': 'vendors/fly.io/migrate.md'
    - 'Northflank': 'vendors/northflank/new_user.md'
    - 'Migration to Northflank': 'vendors/northflank/migrate.md'
    - 'Oracle Cloud': 'vendors/oracle/new_user.md'
    - 'Google Cloud': 'vendors/google/new_user.md'
    - 'MVPS': 'vendors/MVPS/new_user.md'
    - 'Digital Ocean': 'vendors/digitalocean/new_user.md'
    - 'Synology NAS': 'vendors/synology/new_user.md'
    - 'NSaaS - T1Pal': 'vendors/T1Pal/new_user.md'
    - 'NSaaS - NS10BE': 'vendors/10BE.md'
- Configure:
    - 'Configure your Nightscout': 'nightscout/setup_variables.md'
    - 'Configure your Uploader': 'uploader/setup.md'
    - 'xDrip+ CareLink bridge': 'uploader/xdripcarelink.md'
    - 'Follower Devices': 'nightscout/downloaders.md'
    - 'Nightscout on your watch': 'nightscout/wearable.md'
    - 'Running multiple sites': 'nightscout/multiadmin.md'
    - 'Closed-loop Systems': 'nightscout/close_loop.md'
- Use:
    - 'Discover your site': 'nightscout/discover.md'
    - 'Secure your site': 'nightscout/security.md'
    - 'Reports': 'nightscout/reports.md'
    - 'Profile Editor': 'nightscout/profile_editor.md'
    - 'Admin Tools': 'nightscout/admin_tools.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
- Update:
    - 'Updating your site': 'update/update.md'
    - 'Redeploying': 'update/redeploy.md'
    - 'Deploy another GitHub branch': 'update/dev_branch.md'
    - 'Heroku Hobby plan upgrade': 'vendors/heroku/hobbyplan.md'
    - 'Heroku Stack Update': 'update/upd_stack.md'
    - 'Heroku Multiple Factor Authentication': 'vendors/heroku/index.md'
    - 'Heroku Downgrade': 'update/downgrade.md'
- Troubleshoot:
    - 'Troubleshooting': 'troubleshoot/troubleshoot.md'
    - 'GitHub': 'troubleshoot/github.md'
    - 'Heroku': 'troubleshoot/heroku.md'
    - 'Railway': 'troubleshoot/railway.md'
    - 'MongoDB Atlas': 'troubleshoot/atlas.md'
    - 'Dexcom bridge': 'troubleshoot/dexcom_bridge.md'
    - 'Cleanup': 'troubleshoot/cleanup.md'
- Translation: 'translate.md'
