site_name: Nightscout
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- Introduction:
    - 'What is Nightscout?': 'index.md'
    - 'How do I upload my data?': 'uploader/uploaders.md'
- Install: 
    - 'Overview': 'nightscout/insights.md'
    - 'Installation': 'nightscout/new_user.md'
- Configure:
    - 'Configure your Nightscout': 'nightscout/setup_variables.md'
    - 'Configure your Uploader': 'uploader/setup.md'
    - 'Secure your site': 'nightscout/security.md'
    - 'Follower Devices': 'nightscout/downloaders.md'
    - 'Nightscout on your watch': 'nightscout/wearable.md'
    - 'Running multiple sites': 'nightscout/multiadmin.md'
    - 'Closed-loop Systems': 'nightscout/close_loop.md'
    - 'Security': 'nightscout/security.md'
- Use:
    - 'Discover your site': 'nightscout/discover.md'
    - 'Secure your site': 'nightscout/security.md'
    - 'Reports': 'nightscout/reports.md'
    - 'Profile Editor': 'nightscout/profile_editor.md'
    - 'Admin Tools': 'nightscout/admin_tools.md'
    - 'Security': 'nightscout/security.md'
- Update:
    - 'Updating your site': 'update/update.md'
    - 'Redeploying': 'update/redeploy.md'
    - 'Attach a new Atlas database': 'update/newdatabase.md'
- Troubleshoot:
    - 'Troubleshooting': 'troubleshoot/troublehoot.md'
    - 'Connection failure': 'troubleshoot/connection_string.md'
    - 'Cleanup': 'troubleshoot/cleanup.md'
